name: Build and Deploy All Aarjava Agents

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.sha }}
      PROJECT_ID: arjava-jkcement-ai
      REGION: asia-south1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set gcloud project and region
      run: |
        gcloud config set project $PROJECT_ID
        gcloud config set run/region $REGION
        gcloud config set run/platform managed

    # ─── Kiln Agent ─────────────────────────────────────────────
    - name: Build KilnAgent
      run: |
        gcloud builds submit agents/kiln_agent \
          --tag gcr.io/$PROJECT_ID/kiln-agent:$TAG

    - name: Deploy KilnAgent
      run: |
        echo "Deploying KilnAgent..."
        gcloud run deploy kiln-agent \
          --image=gcr.io/$PROJECT_ID/kiln-agent:$TAG \
          --region=$REGION \
          --allow-unauthenticated \
          --set-env-vars PROJECT_ID=$PROJECT_ID

    # ─── Cooler Agent ───────────────────────────────────────────
    - name: Build CoolerAgent
      run: |
        gcloud builds submit agents/cooler_agent \
          --tag gcr.io/$PROJECT_ID/cooler-agent:$TAG

    - name: Deploy CoolerAgent
      run: |
        echo "Deploying CoolerAgent..."
        gcloud run deploy cooler-agent \
          --image=gcr.io/$PROJECT_ID/cooler-agent:$TAG \
          --region=$REGION \
          --allow-unauthenticated \
          --set-env-vars PROJECT_ID=$PROJECT_ID

    # ─── Mix Agent ──────────────────────────────────────────────
    - name: Build MixAgent
      run: |
        gcloud builds submit agents/mix_agent \
          --tag gcr.io/$PROJECT_ID/mix-agent:$TAG

    - name: Deploy MixAgent
      run: |
        echo "Deploying MixAgent..."
        gcloud run deploy mix-agent \
          --image=gcr.io/$PROJECT_ID/mix-agent:$TAG \
          --region=$REGION \
          --allow-unauthenticated \
          --set-env-vars PROJECT_ID=$PROJECT_ID

    # ─── Maintenance Agent ──────────────────────────────────────
    - name: Build MaintenanceAgent
      run: |
        gcloud builds submit agents/maintenance_agent \
          --tag gcr.io/$PROJECT_ID/maintenance-agent:$TAG

    - name: Deploy MaintenanceAgent
      run: |
        echo "Deploying MaintenanceAgent..."
        gcloud run deploy maintenance-agent \
          --image=gcr.io/$PROJECT_ID/maintenance-agent:$TAG \
          --region=$REGION \
          --allow-unauthenticated \
          --set-env-vars PROJECT_ID=$PROJECT_ID