name: Build and Deploy All Arjava Agents

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.sha }} 
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set gcloud project and region
      run: |
        gcloud config set project arjava-jkcement-ai
        gcloud config set run/region asia-south1

    # ─── Kiln Agent ─────────────────────────────────────────────
    - name: Build KilnAgent
      run: |
        gcloud builds submit agents/kiln_agent --tag gcr.io/arjava-jkcement-ai/kiln-agent:$TAG
      env:
        TAG: ${{ env.TAG }}

    - name: Deploy KilnAgent
      run: |
        set -e
        echo "Deploying KilnAgent..."
        gcloud run deploy kiln-agent
          --image=gcr.io/arjava-jkcement-ai/kiln-agent:$TAG
          --platform=managed
          --allow-unauthenticated
          --set-env-vars PROJECT_ID=arjava-jkcement-ai
      env:  
        TAG: ${{ env.TAG }} 

    # ─── Cooler Agent ───────────────────────────────────────────
    - name: Build CoolerAgent
      run: |
        gcloud builds submit agents/cooler_agent --tag gcr.io/arjava-jkcement-ai/cooler-agent:$TAG
      env:
        TAG: ${{ env.TAG }}

    - name: Deploy CoolerAgent
      run: |
        gcloud run deploy cooler-agent 
          --image=gcr.io/arjava-jkcement-ai/cooler-agent:$TAG
          --platform=managed 
          --allow-unauthenticated 
          --set-env-vars PROJECT_ID=arjava-jkcement-ai
      env:
        TAG: ${{ env.TAG }}

    # ─── Mix Agent ──────────────────────────────────────────────
    - name: Build MixAgent
      run: |
        gcloud builds submit agents/mix_agent --tag gcr.io/arjava-jkcement-ai/mix-agent:$TAG
      env:
        TAG: ${{ env.TAG }}

    - name: Deploy MixAgent
      run: |
        gcloud run deploy mix-agent
          --image=gcr.io/arjava-jkcement-ai/mix-agent:$TAG
          --platform=managed
          --allow-unauthenticated
          --set-env-vars PROJECT_ID=arjava-jkcement-ai
      env:
        TAG: ${{ env.TAG }}

    # ─── Maintenance Agent ──────────────────────────────────────
    - name: Build MaintenanceAgent
      run: |
        gcloud builds submit agents/maintenance_agent
          --tag gcr.io/arjava-jkcement-ai/maintenance-agent:$TAG
      env:
        TAG: ${{ env.TAG }}

    - name: Deploy MaintenanceAgent
      run: |
        gcloud run deploy maintenance-agent
          --image=gcr.io/arjava-jkcement-ai/maintenance-agent:$TAG  
          --platform=managed
          --region=asia-south1
          --allow-unauthenticated
          --set-env-vars PROJECT_ID=arjava-jkcement-ai
      env:
        TAG: ${{ env.TAG }}